format='''$directory$package$git_branch$git_status
$character
'''

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
style = "bold fg:64"
truncate_to_repo = false
truncation_length = -1

[git_branch]
format = "on [$symbol$branch]($style)"
style = "bold fg:61"

[git_status]
conflicted = "*"
deleted = "*"
diverged = ""
format = "[$all_status]($style)"
modified = "*"
renamed = "*"
staged = ""
stashed = ""
style = "bold fg:61"
untracked = "*"

[package]
symbol = "☱ "

[prompt]
add_newline = false
