format='''${custom.tab}$directory$package$git_branch$git_status$nim$zig$nodejs$python
$hostname$character
'''
add_newline = false

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[directory]
style = "bold fg:64"
truncate_to_repo = false
truncation_length = -1

[git_branch]
format = "on [$symbol$branch]($style)"
style = "bold fg:61"

[nim]
format = " [$symbol($version )]($style)"
symbol = "nim "

[nodejs]
format = " [$symbol($version )]($style)"
symbol = "node "

[python]
format = ' [${symbol}${pyenv_prefix}($virtualenv)]($style)'
symbol = ""

[zig]
format = " [$symbol($version )]($style)"
symbol = "zig "

# Use something like this?
# ᐜ ᐝ ᐞ ᐟ ᐠ ᐡ ᐢ ᐣ ᐤ ᐥ ᐦ ᐨ ᐩ ᐪ ᑉ ᑊ ᑋ ᒃ ᒄ ᒡ ᒢ ᒻ ᒼ ᒽ ᒾ ᓐ ᓑ ᓒ ᓪ ᓫ ᔅ ᔆ ᔇ ᔈ ᔉ ᔊ ᔋ ᔥ ᔾ ᔿ ᕐ ᕑ ᕝ ᕪ ᕻ ᕽ ᖅ ᖕ ᖖ ᖟ ᖦ ᖮ ᗮ ᘁ ᙆ ᙇ ᙚ
[git_status]
conflicted = "*"
deleted = "*"
diverged = ""
format = "[$all_status]($style)"
modified = "*"
renamed = "*"
staged = ""
stashed = ""
style = "bold fg:61"
untracked = "*"

[hostname]
ssh_only = true
format = '\[[$hostname]($style)\] '

[package]
format = "| [$symbol$version]($style) "
symbol = "☱ "
display_private = true

[custom]

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship|cut -d ' ' -f 2"
when = "tab --starship"
shell = ["sh"]
format = '\[[$output]($style)\] '
style = "bold blue"
